# Optional GCP container image. Persist registries outside the image under
# /var/lib/hoodatm and inject the root-owned environment file at runtime.

FROM node:24.18.0-bookworm-slim AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

FROM node:24.18.0-bookworm-slim AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Public values are embedded at build time.
ARG NEXT_PUBLIC_ROBINHOOD_NETWORK=mainnet
ARG NEXT_PUBLIC_ROBINHOOD_TESTNET_RPC_URL=https://rpc.testnet.chain.robinhood.com
ARG NEXT_PUBLIC_ROBINHOOD_MAINNET_RPC_URL=https://rpc.mainnet.chain.robinhood.com
ARG NEXT_PUBLIC_X_LAUNCH_POST_ID=2082123080462446795
ARG NEXT_PUBLIC_GAME_LIVE=false
ARG NEXT_PUBLIC_TOKEN_REVEALED=false
ARG NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=
ARG NEXT_PUBLIC_HOODATM_GAME_ADDRESS=
ARG NEXT_PUBLIC_HOODATM_GANG_ADDRESS=
ARG NEXT_PUBLIC_GANGSTER_ORACLE_ADDRESS=
ARG NEXT_PUBLIC_GANGSTER_HOLDING_ORACLE_ADDRESS=
ARG NEXT_PUBLIC_HOODATM_RESOLVER_ADDRESS=

ENV NEXT_PUBLIC_ROBINHOOD_NETWORK=$NEXT_PUBLIC_ROBINHOOD_NETWORK \
    NEXT_PUBLIC_ROBINHOOD_TESTNET_RPC_URL=$NEXT_PUBLIC_ROBINHOOD_TESTNET_RPC_URL \
    NEXT_PUBLIC_ROBINHOOD_MAINNET_RPC_URL=$NEXT_PUBLIC_ROBINHOOD_MAINNET_RPC_URL \
    NEXT_PUBLIC_X_LAUNCH_POST_ID=$NEXT_PUBLIC_X_LAUNCH_POST_ID \
    NEXT_PUBLIC_GAME_LIVE=$NEXT_PUBLIC_GAME_LIVE \
    NEXT_PUBLIC_TOKEN_REVEALED=$NEXT_PUBLIC_TOKEN_REVEALED \
    NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=$NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID \
    NEXT_PUBLIC_HOODATM_GAME_ADDRESS=$NEXT_PUBLIC_HOODATM_GAME_ADDRESS \
    NEXT_PUBLIC_HOODATM_GANG_ADDRESS=$NEXT_PUBLIC_HOODATM_GANG_ADDRESS \
    NEXT_PUBLIC_GANGSTER_ORACLE_ADDRESS=$NEXT_PUBLIC_GANGSTER_ORACLE_ADDRESS \
    NEXT_PUBLIC_GANGSTER_HOLDING_ORACLE_ADDRESS=$NEXT_PUBLIC_GANGSTER_HOLDING_ORACLE_ADDRESS \
    NEXT_PUBLIC_HOODATM_RESOLVER_ADDRESS=$NEXT_PUBLIC_HOODATM_RESOLVER_ADDRESS

RUN npm run build

FROM node:24.18.0-bookworm-slim AS runner
WORKDIR /app
ENV NODE_ENV=production \
    PORT=3000 \
    HOSTNAME=0.0.0.0

COPY --from=builder /app/server.js ./server.js
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/.next/standalone ./.next/standalone

CMD ["node", "server.js"]
